version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/myriad/app
      - /home/myriad/app/node_modules
      - /home/myriad/app/.next
    environment:
      - HOST=0.0.0.0
      - PORT=3002
    ports:
      - 3002:3002
