version: '3.1'

services:
  myriad-dashboard:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=3000
