version: '3'

services:
  web:
    image: myriadsocial/myriad-web:1.0.0
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3002:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.5
        aliases:
          - web

networks:
  myriad:
    external: true
