
#
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: mongo
  namespace: depend
spec:
  clusterIP: 172.21.8.250
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
