{{- if .Values.config.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-web.apiSecretName" . }}
type: Opaque
data:
  key: {{ .Values.config.apiKey | b64enc }}

---

{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-web.firebaseSecretName" . }}
type: Opaque
data:
  projectId: {{ .Values.config.firebase.projectId | b64enc }}
  apiKey: {{ .Values.config.firebase.apiKey | b64enc }}
  messagingSenderId: {{ .Values.config.firebase.messagingSenderId | b64enc }}
  appId: {{ .Values.config.firebase.appId | b64enc }}
  measurementId: {{ .Values.config.firebase.measurementId | b64enc }}

---
{{- if .Values.config.sentry.dns }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-web.sentrySecretName" . }}
type: Opaque
data:
  dns: {{ .Values.config.sentry.dns | b64enc }}

---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-web.facebookSecretName" . }}
type: Opaque
data:
  appId: {{ .Values.config.facebook.appId | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-web.twitterSecretName" . }}
type: Opaque
data:
  bearerToken: {{ .Values.config.twitter.bearerToken | b64enc }}
