name: Check Links

on:
  pull_request:
    branches:
      - master
      - main
      - development
  push:
    branches:
      - master
      - main
      - development

jobs:
  check-link-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Link Markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/mlc_config.json"
